name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  postgresql_18:
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 18
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  postgresql_oldest:
    needs: [postgresql_18]
    uses: ./.github/workflows/oldest-postgres.yml
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  postgresql_17:
    needs: [postgresql_18]
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 17
      python-versions: '["3.11", "3.12", "3.13", "3.14", "pypy-3.11"]'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  postgresql_16:
    needs: [postgresql_17]
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 16
      python-versions: '["3.12", "3.13", "3.14"]'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  postgresql_15:
    needs: [postgresql_16]
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 15
      python-versions: '["3.14"]'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  postgresql_14:
    needs: [postgresql_15]
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 14
      python-versions: '["3.14"]'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  macos_postgres_18:
    needs: [postgresql_18]
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 18
      os: macos-latest
      python-versions: '["3.12", "3.13", "3.14"]'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  macos_postgres_17:
    needs: [postgresql_17, macos_postgres_18]
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 17
      os: macos-latest
      python-versions: '["3.12", "3.13", "3.14"]'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  macos_postgres_16:
    needs: [postgresql_16, macos_postgres_17]
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 16
      os: macos-latest
      python-versions: '["3.13", "3.14"]'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  windows_postgres_18:
    needs: [postgresql_18]
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 18
      os: windows-latest
      python-versions: '["3.12", "3.13", "3.14"]'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  windows_postgres_17:
    needs: [postgresql_17, windows_postgres_18]
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 17
      os: windows-latest
      python-versions: '["3.12", "3.13", "3.14"]'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  windows_postgres_16:
    needs: [postgresql_16, windows_postgres_17]
    uses: ./.github/workflows/single-postgres.yml
    with:
      postgresql: 16
      os: windows-latest
      python-versions: '["3.13", "3.14"]'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  docker_postgresql_18:
    needs: [postgresql_18]
    uses: ./.github/workflows/dockerised-postgres.yml
    with:
      postgresql: 18
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  docker_postgresql_17:
    needs: [postgresql_17, docker_postgresql_18]
    uses: ./.github/workflows/dockerised-postgres.yml
    with:
      postgresql: 17
      python-versions: '["3.11", "3.12", "3.13", "3.14"]'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  docker_postgresql_16:
    needs: [postgresql_16, docker_postgresql_18]
    uses: ./.github/workflows/dockerised-postgres.yml
    with:
      postgresql: 16
      python-versions: '["3.12", "3.13", "3.14"]'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  docker_postgresql_15:
    needs: [postgresql_15, docker_postgresql_16]
    uses: ./.github/workflows/dockerised-postgres.yml
    with:
      postgresql: 15
      python-versions: '["3.13", "3.14"]'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  docker_postgresql_14:
    needs: [postgresql_14, docker_postgresql_15]
    uses: ./.github/workflows/dockerised-postgres.yml
    with:
      postgresql: 14
      python-versions: '["3.14"]'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
